using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Xunit;

namespace MigrationSafety.Analyzers.Tests
{
    public class MigrationSafetyAnalyzerTests
    {
        [Fact]
        public async Task Test_Analyzer_Reports_Diagnostics_In_AutoGenerated_File()
        {
            // Arrange
            var test = new AnalyzerTests();
            test.AddSource(@"
using System;

namespace AutoGenerated
{
    public class Program
    {
        public static void Main(string[] args)
        {
            DropColumn();
        }
    }
}
");

            // Act
            var results = await test.RunAllAsync();

            // Assert
            results.Should().ContainSingle();
            results.First().Diagnostic.Id.Should().Be(DiagnosticIds.DropColumn);
        }
    }
}
