using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace MigrationSafety.Analyzers
{
    /// <summary>
    /// Flags destructive or lock-heavy operations inside EF Core migrations before they reach
    /// production. Every rule inspects <c>migrationBuilder.*</c> invocations in the syntax tree
    /// and reports on the method-name token so the squiggle lands on the operation itself.
    /// </summary>
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public sealed class MigrationSafetyAnalyzer : DiagnosticAnalyzer
    {
        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics { get; } =
            ImmutableArray.Create(
                Descriptors.DropColumn,
                Descriptors.NonConcurrentIndex,
                Descriptors.TableRewrite,
                Descriptors.DropTable,
                Descriptors.AddNotNullColumn,
                Descriptors.RenameColumn);

        public override void Initialize(AnalysisContext context)
        {
            context.EnableConcurrentExecution();
            // Migration files are generated code and are the entire point of this
            // analyzer, so opt in to analyzing and reporting on them.
            // With the default (None), any file carrying an <auto-generated> header - e.g. migration
            // Designer files - would silently be skipped.
            context.ConfigureGeneratedCodeAnalysis(
                GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics);
            context.RegisterSyntaxNodeAction(AnalyzeInvocation, SyntaxKind.InvocationExpression);
        }

        private static void AnalyzeInvocation(SyntaxNodeAnalysisContext context)
        {
            var invocation = (InvocationExpressionSyntax)context.Node;
            if (!(invocation.Expression is MemberAccessExpressionSyntax memberAccess))
            {
                return;
            }

            if (!(context.SemanticModel.GetSymbolInfo(invocation).Symbol is IMethodSymbol method))
            {
                return;
            }

            if (!MigrationBuilderCalls.IsMigrationBuilderMethod(method))
            {
                return;
            }

            // Only analyze invocations in actual EF Core Migration classes
            if (!IsInMigrationClass(context))
            {
                return;
            }

            // Optionally exclude Down() methods unless explicitly opted in via editorconfig
            if (!ShouldAnalyzeDownMethod(context) && IsInDownMethod(context))
            {
                return;
            }

            if (SuppressionComment.IsReviewed(invocation))
            {
                return;
            }

            var reportLocation = memberAccess.Name.GetLocation();

            switch (method.Name)
            {
                case "DropColumn":
                    Report(context, invocation, method, Descriptors.DropColumn, reportLocation, "name", "table");
                    break;

                case "DropTable":
                    ReportSingle(context, invocation, method, Descriptors.DropTable, reportLocation, "name");
                    break;

                case "CreateIndex":
                    // Skip diagnostic if the index is created online/concurrently
                    if (!MigrationBuilderCalls.HasOnlineIndexAnnotation(invocation, context.SemanticModel))
                    {
                        Report(context, invocation, method, Descriptors.NonConcurrentIndex, reportLocation, "name", "table");
                    }
                    break;

                case "AlterColumn":
			AnalyzeAlterColumn(context, invocation, method, reportLocation);
                    break;

                case "AddColumn":
                    AnalyzeAddColumn(context, invocation, method, reportLocation);
                    break;

                case "RenameColumn":
                    Report(context, invocation, method, Descriptors.RenameColumn, reportLocation, "name", "newName");
                    break;

                case "RenameTable":
                    Report(context, invocation, method, Descriptors.RenameColumn, reportLocation, "name", "newName");
                    break;
            }
        }

        /// <summary>
        /// Determines whether the current invocation is within a class that derives from
        /// <c>Microsoft.EntityFrameworkCore.Migrations.Migration</c>.
        /// </summary>
        private static bool IsInMigrationClass(SyntaxNodeAnalysisContext context)
        {
            // Walk up the syntax tree to find the containing class declaration
            var current = context.Node;
            while (current != null)
            {
                if (current is ClassDeclarationSyntax classDeclaration)
                {
                    // Get the semantic model symbol for the class
                    var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);
                    if (classSymbol != null)
                    {
                        // Check if the class derives from Migration (directly or indirectly)
                        return IsMigrationType(classSymbol.BaseType);
                    }
                    return false;
                }

                current = current.Parent;
            }

            return false;
        }

        /// <summary>
        /// Recursively checks if a type derives from Microsoft.EntityFrameworkCore.Migrations.Migration
        /// </summary>
        private static bool IsMigrationType(ITypeSymbol? type)
        {
            if (type == null)
            {
                return false;
            }

            // Check the full type name
            if (type.ToDisplayString() == "Microsoft.EntityFrameworkCore.Migrations.Migration")
            {
                return true;
            }

            // Recursively check base types
            return IsMigrationType(type.BaseType);
        }

        /// <summary>
        /// Determines whether the current invocation is within a Down() method.
        /// </summary>
        private static bool IsInDownMethod(SyntaxNodeAnalysisContext context)
        {
            // Walk up the syntax tree to find the containing method
            var current = context.Node;
            while (current != null)
            {
                if (current is MethodDeclarationSyntax methodDeclaration)
                {
                    // Check if the method is named "Down"
                    if (methodDeclaration.Identifier.Text == "Down")
                    {
                        return true;
                    }
                    return false;
                }

                current = current.Parent;
            }

            return false;
        }

        /// <summary>
        /// Determines whether Down() methods should be analyzed based on editorconfig configuration.
        /// Returns true if analysis is enabled, false to exclude Down() methods.
        /// </summary>
        private static bool ShouldAnalyzeDownMethod(SyntaxNodeAnalysisContext context)
        {
            // Check if the analyzer is configured to analyze Down() methods
            // The configuration key is: mig_safety.analyze_down
            // Default is false (exclude Down() methods)

            // In Roslyn analyzers, we can check additional files or use analyzer config
            // For now, we'll implement a simple check that can be extended with proper config
            // The actual implementation would use context.Options.AnalyzerConfigOptionsProvider
            // For the MVP, we'll assume the default behavior is to exclude Down()

            // This method is a placeholder that can be extended with proper configuration
            // For the MVP, we'll return false to exclude Down() by default as requested
            return false;
        }

        private static void AnalyzeAlterColumn(
            SyntaxNodeAnalysisContext context,
            InvocationExpressionSyntax invocation,
            IMethodSymbol method,
            Location reportLocation)
        {
            // Analyze the parameters to determine the appropriate severity
            var diagnostic = AnalyzeAlterColumnParameters(invocation, method, context, reportLocation);

            context.ReportDiagnostic(diagnostic);
        }

        private static Diagnostic AnalyzeAlterColumnParameters(
            InvocationExpressionSyntax invocation,
            IMethodSymbol method,
            SyntaxNodeAnalysisContext context,
            Location reportLocation)
        {
            // Analyze nullable parameter
            var nullableDiagnostic = AnalyzeNullableChange(invocation, method, context, reportLocation);
            if (nullableDiagnostic != null)
            {
                return nullableDiagnostic;
            }

            // Analyze type narrowing (maxLength, precision, scale)
            var typeNarrowingDiagnostic = AnalyzeTypeNarrowing(invocation, method, context, reportLocation);
            if (typeNarrowingDiagnostic != null)
            {
                return typeNarrowingDiagnostic;
            }

            // Default to warning for other AlterColumn changes
            var first = MigrationBuilderCalls.GetStringArgument(invocation, method, "name") ?? "?";
            var second = MigrationBuilderCalls.GetStringArgument(invocation, method, "table") ?? "?";
            return Diagnostic.Create(Descriptors.TableRewrite, reportLocation, first, second);
        }

        private static Diagnostic? AnalyzeNullableChange(
            InvocationExpressionSyntax invocation,
            IMethodSymbol method,
            SyntaxNodeAnalysisContext context,
            Location reportLocation)
        {
            var nullableArg = MigrationBuilderCalls.GetNamedArgument(invocation, method, "nullable");
            if (nullableArg == null)
            {
                return null; // No nullable parameter change
            }

            // Check if the nullable argument is a literal
            if (nullableArg.Expression is LiteralExpressionSyntax literal)
            {
                var newNullable = literal.Token.Value as bool?;
                if (newNullable.HasValue)
                {
                    // For now, we'll use a simplified approach:
                    // - If nullable is explicitly set to false, it's a narrowing operation (Warning)
                    // - If nullable is explicitly set to true, it's a widening operation (Info)
                    // - If nullable is not specified, we can't determine the change

                    var first = MigrationBuilderCalls.GetStringArgument(invocation, method, "name") ?? "?";
                    var second = MigrationBuilderCalls.GetStringArgument(invocation, method, "table") ?? "?";

                    if (newNullable == false)
                    {
                        // false -> narrowing, data loss risk - Warning
                        return Diagnostic.Create(Descriptors.TableRewrite, invocation.GetLocation(), first, second);
                    }
                    else if (newNullable == true)
                    {
                        // true -> widening, safe operation - Info
                        var descriptor = new DiagnosticDescriptor(
                            id: DiagnosticIds.TableRewrite,
                            title: Descriptors.TableRewrite.Title,
                            messageFormat: Descriptors.TableRewrite.MessageFormat,
                            category: DiagnosticIds.Category,
                            defaultSeverity: DiagnosticSeverity.Info,
                            isEnabledByDefault: Descriptors.TableRewrite.IsEnabledByDefault,
                            description: "Making a column nullable is a safe operation that doesn't rewrite table data.",
                            helpLinkUri: Descriptors.TableRewrite.HelpLinkUri);
                        return Diagnostic.Create(descriptor, invocation.GetLocation(), first, second);
                    }
                }
            }

            return null;
        }

        private static Diagnostic? AnalyzeTypeNarrowing(
            InvocationExpressionSyntax invocation,
            IMethodSymbol method,
            SyntaxNodeAnalysisContext context,
            Location reportLocation)
        {
            // Check for maxLength narrowing
            var maxLengthArg = MigrationBuilderCalls.GetNamedArgument(invocation, method, "maxLength");
            if (maxLengthArg != null)
            {
                if (maxLengthArg.Expression is LiteralExpressionSyntax maxLengthLiteral)
                {
                    var maxLengthValue = maxLengthLiteral.Token.Value as int?;
                    if (maxLengthValue.HasValue && maxLengthValue.Value >= 0)
                    {
                        // Type narrowing detected - Warning level
                        var first = MigrationBuilderCalls.GetStringArgument(invocation, method, "name") ?? "?";
                        var second = MigrationBuilderCalls.GetStringArgument(invocation, method, "table") ?? "?";
                        return Diagnostic.Create(Descriptors.TableRewrite, invocation.GetLocation(), first, second);
                    }
                }
            }

            // Check for type parameter narrowing (e.g., decimal precision/scale changes)
            // This would require more sophisticated analysis in a real implementation

            return null;
        }

        private static void AnalyzeAddColumn(
            SyntaxNodeAnalysisContext context,
            InvocationExpressionSyntax invocation,
            IMethodSymbol method,
            Location reportLocation)
        {
            // Check if nullable: false is explicitly set
            var nullableArg = MigrationBuilderCalls.GetNamedArgument(invocation, method, "nullable");
            if (nullableArg != null)
            {
                // Check if the nullable argument is the literal false
                var expression = nullableArg.Expression;
                if (expression is LiteralExpressionSyntax literal && literal.Token.Value is false)
                {
                    // Check if defaultValue or defaultValueSql is present
                    var hasDefaultValue = MigrationBuilderCalls.GetNamedArgument(invocation, method, "defaultValue") != null;
                    var hasDefaultValueSql = MigrationBuilderCalls.GetNamedArgument(invocation, method, "defaultValueSql") != null;

                    if (!hasDefaultValue && !hasDefaultValueSql)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            Descriptors.AddNotNullColumn,
                            reportLocation,
                            method.Name));
                    }
                }
            }
        }

        private static void Report(
            SyntaxNodeAnalysisContext context,
            InvocationExpressionSyntax invocation,
            IMethodSymbol method,
            DiagnosticDescriptor descriptor,
            Location location,
            string firstArg,
            string secondArg)
        {
            var first = MigrationBuilderCalls.GetStringArgument(invocation, method, firstArg) ?? "?";
            var second = MigrationBuilderCalls.GetStringArgument(invocation, method, secondArg) ?? "?";
            context.ReportDiagnostic(Diagnostic.Create(descriptor, location, first, second));
        }

        private static void ReportSingle(
            SyntaxNodeAnalysisContext context,
            InvocationExpressionSyntax invocation,
            IMethodSymbol method,
            DiagnosticDescriptor descriptor,
            Location location,
            string firstArg)
        {
            var first = MigrationBuilderCalls.GetStringArgument(invocation, method, firstArg) ?? "?";
            context.ReportDiagnostic(Diagnostic.Create(descriptor, location, first));
        }
    }
}
